In [1]:
import numpy as np

from struct import pack_into, unpack_from

In [12]:
X =np.array([[1,2,3,4],[4,5,6,7]])
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])

array([[1.66666667, 1.66666667],
       [1.66666667, 1.66666667]])

In [13]:
np.cov(x,y),np.cov(x.T,y.T)

(array([[1.66666667, 1.66666667],
        [1.66666667, 1.66666667]]),
 array([[1.66666667, 1.66666667],
        [1.66666667, 1.66666667]]))

In [14]:
X,np.cov(X)


(array([[1, 2, 3, 4],
        [4, 5, 6, 7]]),
 array([[1.66666667, 1.66666667],
        [1.66666667, 1.66666667]]))