# 2.2 数据操作

In [27]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.6.0+cu101


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [28]:
x = torch.empty(5, 3)
print(x)

tensor([[2.9455e-33, 6.8523e-43, 2.9456e-33],
        [6.8523e-43, 2.9456e-33, 6.8523e-43],
        [2.9456e-33, 6.8523e-43, 2.9456e-33],
        [6.8523e-43, 2.9456e-33, 6.8523e-43],
        [2.9456e-33, 6.8523e-43, 2.9457e-33]])


创建一个5x3的随机初始化的`Tensor`:



In [29]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [30]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [31]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [32]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的数据类型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])


我们可以通过`shape`或者`size()`来获取`Tensor`的形状:

In [33]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其实就是一个tuple, 支持所有tuple的操作。

In [53]:
print('-----------------------------')
print(torch.rand(5, 3)) # 创建一个5x3的随机初始化的Tensor  随机样本位于[0, 1)均匀分布中
print(torch.Tensor(5,3).uniform_(0,1)) # 均匀分布

x1 = torch.randn(5, 3)
print(x1) # 标准正态分布中的样本,从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数。
x2 = torch.normal(0, 1, (5,3)) # torch.Tensor(5,3).normal_
print(x2) # 正态分布中的样本, 指定均值means和标准差std的离散正态分布中抽取的一组随机数。

print(x1.mean(), x2.mean())
print('-----------------------------')

print(torch.arange(0, 12, 2)) # 从s到e，步长为step tensor([ 0,  2,  4,  6,  8, 10])
print(torch.linspace(0, 12, 3)) # 从s到e，均匀切分成steps份   tensor([ 0.,  6., 12.])

print(torch.randperm(10)) # 把1到10这些数随机打乱得到的一个数字序列。

-----------------------------
tensor([[0.2038, 0.6511, 0.7745],
        [0.4369, 0.5191, 0.6159],
        [0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143],
        [0.9351, 0.9412, 0.5995]])
tensor([[0.0652, 0.5460, 0.1872],
        [0.0340, 0.9442, 0.8802],
        [0.0012, 0.5936, 0.4158],
        [0.4177, 0.2711, 0.6923],
        [0.2038, 0.6833, 0.7529]])
tensor([[ 0.1894, -0.2190,  2.0576],
        [-0.0354,  0.0627, -0.7663],
        [ 1.0993,  2.7565,  0.1753],
        [-0.9315, -1.5055, -0.6610],
        [ 1.3232,  0.0371, -0.2849]])
tensor([[-0.1334,  1.8929,  3.1110],
        [-0.4584, -0.3360, -1.5700],
        [ 1.2315,  1.3946,  1.1711],
        [ 0.4335, -1.7343, -1.3360],
        [ 0.8871,  0.7680,  0.0571]])
tensor(0.2198) tensor(0.3586)
-----------------------------
tensor([ 0,  2,  4,  6,  8, 10])
tensor([ 0.,  6., 12.])
tensor([2, 8, 4, 3, 9, 6, 1, 0, 5, 7])


## 2.2.2 操作
### 算术操作
* **加法形式一**

In [34]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


* **加法形式二**

In [35]:
print(torch.add(x, y))

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


In [36]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


* **加法形式三、inplace**

In [37]:
print(y.add(x))
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])
tensor([[ 1.3967,  1.0892,  0.4369],
        [ 1.6995,  2.0453,  0.6539],
        [-0.1553,  3.7016, -0.3599],
        [ 0.7536,  0.0870,  1.2274],
        [ 2.5046, -0.1913,  0.4760]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

index_select(input, dim, index)	在指定维度dim上选取，比如选取某些行、某些列

masked_select(input, mask)	例子如上，a[a>0]，使用ByteTensor进行选取

nonzero(input)	非0元素的下标

gather(input, dim, index)	根据index，在dim维度上选取数据，输出的size与index一样

In [61]:
y = x[0, :]
print(y)
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了
print(torch.nonzero(x))

tensor([1, 2])
tensor([2, 3])
tensor([2, 3])
tensor([[0, 0],
        [0, 1]])


<ipython-input-61-32a9b3d98ed2>:6: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:766.)
  print(torch.nonzero(x))


### 改变形状
用`view()`来改变`Tensor`的形状：
view能干的reshape都能干

In [39]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

如果我们对A进行截取、转置或修改等操作后赋值给B，则B的数据共享A的存储区，存储区的数据数量没变，变化的只是B的头信息区对数据的索引方式。

In [52]:
a = torch.arange(5)  # 初始化张量 a 为 [0, 1, 2, 3, 4]
b = a[2:]            # 截取张量a的部分值并赋值给b，b其实只是改变了a对数据的索引方式
print('a:', a)
print('b:', b)
print('ptr of storage of a:', a.storage().data_ptr())  # 打印a的存储区地址
print('ptr of storage of b:', b.storage().data_ptr())  # 打印b的存储区地址,可以发现两者是共用存储区

b[1] = 0    # 修改b中索引为1，即a中索引为3的数据为0
print('a:', a)
print('b:', b)
print('ptr of storage of a:', a.storage().data_ptr())  # 打印a的存储区地址,可以发现a的相应位置的值也跟着改变，说明两者是共用存储区
print('ptr of storage of b:', b.storage().data_ptr())  # 打印b的存储区地址

a: tensor([0, 1, 2, 3, 4])
b: tensor([2, 3, 4])
ptr of storage of a: 2100258114432
ptr of storage of b: 2100258114432
a: tensor([0, 1, 2, 0, 4])
b: tensor([2, 0, 4])
ptr of storage of a: 2100258114432
ptr of storage of b: 2100258114432


In [40]:
x += 1
print(x)
print(y) # 也加了1

tensor([[2.6035, 2.8110, 1.9549],
        [1.8797, 2.0482, 0.9555],
        [0.2771, 3.8663, 0.4345],
        [1.1604, 0.9746, 2.0739],
        [3.2628, 0.0825, 0.7749]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [41]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 1.6035,  1.8110,  0.9549],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])
tensor([2.6035, 2.8110, 1.9549, 1.8797, 2.0482, 0.9555, 0.2771, 3.8663, 0.4345,
        1.1604, 0.9746, 2.0739, 3.2628, 0.0825, 0.7749])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [42]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.3466])
2.3466382026672363


## stride 以及reshape和view的区别

In [60]:
a = torch.arange(6).reshape(2, 3)  # 初始化张量 a
b = torch.arange(6).reshape(3, 2)  # 初始化张量 b
print('a:', a)
print('stride of a:', a.stride())  # 打印a的stride
print('b:', b)
print('stride of b:', b.stride())  # 打印b的stride

print(a.t().stride())
print(a.T.stride())
a.T.contiguous().view(2,3) # a.T.view(2,3)报错，不符合contiguous连续性（stride的第二个维度=1）
# b = a.permute(1, 0).contiguous()       # 转置,并转换为符合连续性条件的tensor

a: tensor([[0, 1, 2],
        [3, 4, 5]])
stride of a: (3, 1)
b: tensor([[0, 1],
        [2, 3],
        [4, 5]])
stride of b: (2, 1)
(1, 3)


tensor([[0, 3, 1],
        [4, 2, 5]])

##  线性函数

In [67]:
print(a)
print(torch.trace(a)) # a.trace() 对角线元素之和(矩阵的迹)

print(a.diag()) # 对角线元素

print(a.triu())# 矩阵的上三角/下三角，可指定偏移量
print(a.tril())
print(a.tril(diagonal=1)) # 矩阵的上三角/下三角，可指定偏移量

# a.inverse() 矩阵的逆
# a.pinverse() 矩阵的伪逆
# a.svd() # 奇异值分解
# dot/cross 内积/外积

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor(4)
tensor([0, 4])
tensor([[0, 1, 2],
        [0, 4, 5]])
tensor([[0, 0, 0],
        [3, 4, 0]])
tensor([[0, 1, 0],
        [3, 4, 5]])


## 2.2.3 广播机制

In [54]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 运算的内存开销

In [44]:
# 前面说了，索引操作是不会开辟新内存的，而像y = x + y这样的运算是会新开内存的，然后将y指向新内存。为了演示这一点，我们可以使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x  #y会新开内存
print(id(y) == id_before)

False


In [45]:
# 如果想指定结果到原来的y的内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们把x + y的结果通过[:]写进y对应的内存中。
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x  #y不会新开内存
print(id(y) == id_before)

True


In [46]:
# 我们还可以使用运算符全名函数中的out参数或者自加运算符+=(也即add_())达到上述效果，例如torch.add(x, y, out=y)和y += x(y.add_(x))。
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

# 注：虽然view返回的Tensor与源Tensor是共享data的（.storage().data_ptr()一致），但是依然是一个新的Tensor（因为Tensor除了包含data外还有一些其他属性），二者id（内存地址）并不一致。

True


## 2.2.5 `Tensor`和NumPy相互转换
**`numpy()`和`from_numpy()`这两个函数产生的`Tensor`和NumPy array实际是共享相同的内存（所以他们之间的转换很快），改变其中一个时另一个也会改变！！！**
还有一个常用的将NumPy中的array转换成Tensor的方法就是`torch.tensor()`, 需要注意的是，此方法总是会进行数据拷贝（就会消耗更多的时间和空间），所以返回的Tensor和原来的数据不再共享内存。
### `Tensor`转NumPy

In [47]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy数组转`Tensor`

In [48]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`将NumPy数组转换成`Tensor`，该方法总是会进行数据拷贝，返回的`Tensor`和原来的数据不再共享内存。

In [49]:
# 用torch.tensor()转换时不会共享内存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [50]:
# 以下代码只有在PyTorch GPU版本上才会执行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

RuntimeError: CUDA error: no kernel image is available for execution on the device