In [3]:
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.layers as layers

# 合并与分割
tf.concat +     合并：要求除了拼接以外所有维度相等
tf.split -      分裂：

tf.stack +      堆：要求所有维度相等
tf.unstack -    不堆叠：

In [10]:
a = tf.ones([4,35,8])
b = tf.ones([2,35,8])
c = tf.concat([a,b],axis=0)
print(c.shape) # (6,35,8)

a1 = tf.ones([4,32,8])
b1 = tf.ones([4,3,8])
c1 = tf.concat([a1,b1],axis=1)
print(c1.shape) #(4,35,8)


a2 = tf.ones([4,35,8])
b2 = tf.ones([4,35,8])
c2 = tf.concat([a2,b2],axis=-1)
print(c2.shape) #(4,35,16)
d2 = tf.stack([a2,b2],axis=0)
print(d2.shape) #(2,4,35,8)
d3 = tf.stack([a2,b2],axis=3)
print(d3.shape) #(4,35,8,2)
d4 = tf.stack([a2,b2],axis=1)
print(d4.shape) #(4,2,35,8)

aa,bb = tf.unstack(d4,axis=1)
print(aa.shape,bb.shape) #(4,35,8) (4,35,8)

# 拆分出了8个  (4, 2, 35)
res = tf.unstack(d4,axis=3)
print(res[0].shape,len(res)) # (4, 2, 35) 8

res2 = tf.split(d4,axis=3,num_or_size_splits=2)
print(res2[0].shape,len(res2)) # (4, 2, 35,4) 2

res3 = tf.split(d4,axis=3,num_or_size_splits=[2,2,4])
print(res3[0].shape,res3[1].shape,res3[2].shape) # (4, 2, 35,2) (4, 2, 35,2) (4, 2, 35,4)

(6, 35, 8)
(4, 35, 8)
(4, 35, 16)
(2, 4, 35, 8)
(4, 35, 8, 2)
(4, 2, 35, 8)
(4, 35, 8) (4, 35, 8)
(4, 2, 35) 8
(4, 2, 35, 4) 2
(4, 2, 35, 2) (4, 2, 35, 2) (4, 2, 35, 4)


# 数据统计
tf.norm  范数

tf.reduce_min/max  最大最小

tf.argmax/argmin 最大最小的index

tf.equal
tf.unique 去重

In [12]:
a = tf.ones([2,2])
print(tf.norm(a)) # 2 元素平方的和开根号
print(tf.sqrt(tf.reduce_sum(tf.square(a)))) # 2 同上

tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [14]:
a = tf.ones([2,2])
print(tf.norm(a,ord=2,axis=1)) # 对某一维度求范数
# ord=2 是2范数：平方和开根号(默认)
# ord=1,1范数：绝对值求和

print(tf.norm(a,ord=1))  # 4

tf.Tensor([1.4142135 1.4142135], shape=(2,), dtype=float32)


In [17]:
a = tf.random.normal([4,10])
print(tf.reduce_min(a),tf.reduce_max(a),tf.reduce_mean(a))
print(tf.reduce_min(a,axis=0))
print(tf.reduce_min(a,axis=1))

tf.Tensor(-3.097243, shape=(), dtype=float32) tf.Tensor(1.3584898, shape=(), dtype=float32) tf.Tensor(-0.47285947, shape=(), dtype=float32)
tf.Tensor(
[-1.4835898  -2.1389592  -1.179907   -3.097243   -2.0984085  -0.85453296
 -1.4654832  -1.3538884  -1.1631044  -1.9023842 ], shape=(10,), dtype=float32)
tf.Tensor([-1.179907  -2.0984085 -3.097243  -1.9023842], shape=(4,), dtype=float32)


In [18]:
a = tf.random.normal([4,10])
print(tf.argmax(a))
print(tf.argmax(a,axis=1))

tf.Tensor([2 0 3 3 3 1 1 2 2 2], shape=(10,), dtype=int64)
tf.Tensor([1 6 0 3], shape=(4,), dtype=int64)


In [20]:
a = tf.constant([1,2,3,4,5])
b = tf.range(5)
print(a,b)

res = tf.equal(a,b)
print(res)
print(tf.reduce_sum(tf.cast(res,dtype=tf.int32)))

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([False False False False False], shape=(5,), dtype=bool)
tf.Tensor(0, shape=(), dtype=int32)


In [24]:
# accuracy
a = tf.constant([[0.1,0.2,0.7],[0.9,0.05,0.05]]) # shape (2,3)

pred = tf.cast(tf.argmax(a,axis=1),dtype=tf.int32)
print(pred)

y = tf.constant([2,1])

correct_count = tf.reduce_sum(tf.cast(tf.equal(y,pred),dtype=tf.int32))
print(correct_count)
print(correct_count/len(y))

tf.Tensor([2 0], shape=(2,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0.5, shape=(), dtype=float64)


In [27]:
a = tf.range(5)
print(tf.unique(a))

a = tf.constant([4,2,2,4,3])
b = tf.unique(a)
print(b )
# 还原
print(tf.gather(b.y,b.idx))

Unique(y=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>)
Unique(y=<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>, idx=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 1, 0, 2])>)
tf.Tensor([4 2 2 4 3], shape=(5,), dtype=int32)


# 张量排序
sort/argsort

topk

top-5 acc

In [28]:
a = tf.random.shuffle(tf.range(5))
print(a)

print(tf.sort(a,direction="DESCENDING"))
idx = tf.argsort(a,direction="DESCENDING")
print(idx)
print(tf.gather(a,idx))

tf.Tensor([4 0 3 2 1], shape=(5,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)
tf.Tensor([0 2 3 4 1], shape=(5,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)


In [30]:
a = tf.random.uniform([3,3],maxval=10,dtype=tf.int32)
print(a)

print(tf.sort(a)) # 对最后一个维度排序
print(tf.argsort(a))

tf.Tensor(
[[3 0 6]
 [3 6 7]
 [7 3 3]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [3 6 7]
 [3 3 7]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 2]
 [0 1 2]
 [1 2 0]], shape=(3, 3), dtype=int32)


In [31]:
a = tf.random.uniform([3,3],maxval=10,dtype=tf.int32)
res = tf.math.top_k(a,2)
print(a)
print(res)

tf.Tensor(
[[8 7 8]
 [1 4 6]
 [6 7 9]], shape=(3, 3), dtype=int32)
TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[8, 8],
       [6, 4],
       [9, 7]])>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1]])>)


# 填充与复制
pad

tile

broadcast

In [33]:
a = tf.reshape(tf.range(9),[3,3])
print(a)

print(tf.pad(a,[[0,0],[0,0]])) # 不填充
# 对于二维来说：【【上面填充行数，下面填充行数】，【左面填充行数，右边填充行数】】
print(tf.pad(a,[[1,0],[0,0]])) # 上面填充一行

# image padding
b = tf.random.normal([4,28,28,3])
c = tf.pad(b,[[0,0],[2,2],[2,2],[0,0]])
print(b.shape,c.shape)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 1 2]
 [3 4 5]
 [6 7 8]], shape=(4, 3), dtype=int32)
(4, 28, 28, 3) (4, 32, 32, 3)


In [35]:
a = tf.reshape(tf.range(9),[3,3])
print(a)

# [1,2]  1表示axis=0 不复制，2表示axis=1 复制一次
print(tf.tile(a,[1,2]))

aa = tf.expand_dims(a,axis=0)
print(aa)
print(tf.tile(aa,[2,1,1]))

print(tf.broadcast_to(aa,[2,3,3]))

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]], shape=(3, 6), dtype=int32)
tf.Tensor(
[[[0 1 2]
  [3 4 5]
  [6 7 8]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]], shape=(2, 3, 3), dtype=int32)


# 张量限幅
clip_by_value

relu

clip_by_norm 等比例放缩

gradient clipping

In [36]:
a = tf.range(10)

print(tf.maximum(a,2))
print(tf.minimum(a,8))
print(tf.clip_by_value(a,2,8))

tf.Tensor([2 2 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 8], shape=(10,), dtype=int32)
tf.Tensor([2 2 2 3 4 5 6 7 8 8], shape=(10,), dtype=int32)


In [37]:
a = a-5
print(a)

print(tf.nn.relu(a))
print(tf.maximum(a,0))

tf.Tensor([-5 -4 -3 -2 -1  0  1  2  3  4], shape=(10,), dtype=int32)
tf.Tensor([0 0 0 0 0 0 1 2 3 4], shape=(10,), dtype=int32)
tf.Tensor([0 0 0 0 0 0 1 2 3 4], shape=(10,), dtype=int32)


In [38]:
a = tf.random.normal([2,2],mean=10)
print(a)

print(tf.norm(a)) # 平方和开根号

aa = tf.clip_by_norm(a,15) # 等比例放缩（不会改变向量的方向）
"""
防止梯度爆炸
grads = tape.gradient(loss, model.trainable_variables)
# MUST clip gradient here or it will disconverge!
grads = [ tf.clip_by_norm(g, 15) for g in grads]
"""
print(aa)
print(tf.norm(aa))


tf.Tensor(
[[ 8.997876  10.502432 ]
 [ 8.71957   10.4255085]], shape=(2, 2), dtype=float32)
tf.Tensor(19.390333, shape=(), dtype=float32)
tf.Tensor(
[[6.960589  8.124486 ]
 [6.7452965 8.064979 ]], shape=(2, 2), dtype=float32)
tf.Tensor(14.999999, shape=(), dtype=float32)


# 高阶特性
where

scatter_nd

meshgrid

In [44]:
a = tf.random.normal([3,3])
print(a)

mask = a > 0
print(mask)

print(tf.boolean_mask(a,mask))

indices = tf.where(mask)
print(indices)

print(tf.gather_nd(a,indices))



tf.Tensor(
[[ 0.08510873 -0.30872864  1.9884948 ]
 [-0.3645098   1.0775615   0.25092733]
 [-0.90860075  2.2727058   1.3190372 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ True False  True]
 [False  True  True]
 [False  True  True]], shape=(3, 3), dtype=bool)
tf.Tensor([0.08510873 1.9884948  1.0775615  0.25092733 2.2727058  1.3190372 ], shape=(6,), dtype=float32)
tf.Tensor(
[[0 0]
 [0 2]
 [1 1]
 [1 2]
 [2 1]
 [2 2]], shape=(6, 2), dtype=int64)
tf.Tensor([0.08510873 1.9884948  1.0775615  0.25092733 2.2727058  1.3190372 ], shape=(6,), dtype=float32)


In [45]:
A = tf.ones([3,3])
B = tf.zeros([3,3])

print(tf.where(mask,A,B))


tf.Tensor(
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 1. 1.]], shape=(3, 3), dtype=float32)


In [46]:
indices = tf.constant([[4],[3],[1],[7]])
updates = tf.constant([9,10,11,12])
shape = tf.constant([8])

print(tf.scatter_nd(indices,updates,shape))


tf.Tensor([ 0 11  0 10  9  0  0 12], shape=(8,), dtype=int32)


In [48]:
indices = tf.constant([[0],[2]])
updates = tf.constant([[[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]],
                       [[5,5,5,5],[6,6,6,6],[7,7,7,7],[8,8,8,8]]])
# updates.shape(2,4,4)
shape = tf.constant([4,4,4])
print(tf.scatter_nd(indices,updates,shape))

tf.Tensor(
[[[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[5 5 5 5]
  [6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]], shape=(4, 4, 4), dtype=int32)


In [50]:
y = tf.linspace(-2.,2,5)
print(y)

x = tf.linspace(-2.,2,5)

points_x,points_y = tf.meshgrid(x,y)

print(points_x) # x轴
print(points_y)


points = tf.stack([points_x,points_y],axis=2)
print(points)

tf.Tensor([-2. -1.  0.  1.  2.], shape=(5,), dtype=float32)
tf.Tensor(
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[-2. -2.]
  [-1. -2.]
  [ 0. -2.]
  [ 1. -2.]
  [ 2. -2.]]

 [[-2. -1.]
  [-1. -1.]
  [ 0. -1.]
  [ 1. -1.]
  [ 2. -1.]]

 [[-2.  0.]
  [-1.  0.]
  [ 0.  0.]
  [ 1.  0.]
  [ 2.  0.]]

 [[-2.  1.]
  [-1.  1.]
  [ 0.  1.]
  [ 1.  1.]
  [ 2.  1.]]

 [[-2.  2.]
  [-1.  2.]
  [ 0.  2.]
  [ 1.  2.]
  [ 2.  2.]]], shape=(5, 5, 2), dtype=float32)
