In [1]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

# 统计学习方法330页

In [2]:
X = np.array([[0,0,1,1,0,0,0,0,0],
               [0,0,0,0,0,1,0,0,1],
               [0,1,0,0,0,0,0,1,0],
               [0,0,0,0,0,0,1,0,1],
               [1,0,0,0,0,1,0,0,0],
               [1,1,1,1,1,1,1,1,1],
               [1,0,1,0,0,0,0,0,0],
               [0,0,0,0,0,0,1,0,1],
               [0,0,0,0,0,2,0,0,1],
               [1,0,1,0,0,0,0,1,0],
               [0,0,0,1,1,0,0,0,0]],dtype=np.float)

svd = TruncatedSVD(n_components=3)

svd.fit_transform(X)

array([[ 1.38328918, -0.83736333, -0.81692134],
       [ 0.87036192, -0.38543119,  0.27976749],
       [ 1.32000154, -1.19067026, -0.31229912],
       [ 1.01586826, -0.62035952,  0.48974764],
       [ 0.86303271, -0.35432506,  0.44524445],
       [ 1.9198404 ,  1.43147084, -1.0177211 ],
       [ 1.10890518,  0.17674957,  1.10213245],
       [ 1.12055552, -0.80100835, -0.00458523],
       [ 1.70944734,  1.14355367,  0.67497538]])

In [3]:
svd.singular_values_


array([3.90941804, 2.60911881, 1.99682784])

In [4]:
svd.components_



array([[ 0.15283556,  0.23746367,  0.13026538,  0.18440432,  0.2161232 ,
         0.74009654,  0.17687585,  0.18440432,  0.3630785 ,  0.2501936 ,
         0.12293617],
       [-0.26603445,  0.37826282, -0.17428415,  0.1939483 ,  0.08727248,
        -0.21114703, -0.29791161,  0.1939483 ,  0.58854128, -0.41557716,
        -0.14317803],
       [ 0.04450319, -0.08595889,  0.06901432,  0.44568964, -0.46011902,
         0.21075317, -0.28320277,  0.44568964, -0.34119818, -0.28435272,
         0.23449128]])