In [6]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

# 统计学习方法330页

In [7]:
X = np.array([[0,0,1,1,0,0,0,0,0],
               [0,0,0,0,0,1,0,0,1],
               [0,1,0,0,0,0,0,1,0],
               [0,0,0,0,0,0,1,0,1],
               [1,0,0,0,0,1,0,0,0],
               [1,1,1,1,1,1,1,1,1],
               [1,0,1,0,0,0,0,0,0],
               [0,0,0,0,0,0,1,0,1],
               [0,0,0,0,0,2,0,0,1],
               [1,0,1,0,0,0,0,1,0],
               [0,0,0,1,1,0,0,0,0]],dtype=np.float)

svd = TruncatedSVD(n_components=3)

svd.fit_transform(X)

array([[ 0.59749809, -0.69411549, -0.08886521],
       [ 0.92834476,  0.98693264,  0.1716451 ],
       [ 0.50926185, -0.45472806, -0.13780971],
       [ 0.72091357,  0.50603416, -0.88996548],
       [ 0.84491593,  0.22770428,  0.91877847],
       [ 2.89334677, -0.5509077 , -0.42083781],
       [ 0.69148162, -0.77728679,  0.56550717],
       [ 0.72091357,  0.50603416, -0.88996548],
       [ 1.41942562,  1.53557413,  0.68131402],
       [ 0.97811137, -1.0842902 ,  0.56780343],
       [ 0.48060887, -0.37356849, -0.46823871]])

In [8]:
svd.singular_values_


array([3.90941804, 2.60911881, 1.99682784])

In [9]:
svd.components_



array([[ 0.35383506,  0.22263209,  0.33764656,  0.25985153,  0.22075733,
         0.49108087,  0.28364968,  0.28662975,  0.43726389],
       [-0.32093722, -0.14772466, -0.45634958, -0.23776591, -0.13580258,
         0.54864149,  0.06774301, -0.3070034 ,  0.43829115],
       [ 0.40910955, -0.14010597,  0.15639762, -0.24526283, -0.22297589,
         0.50966892, -0.55194165,  0.00229626, -0.33802383]])