## Array attributes
### 下列属性包含关于数组的内存布局的信息
ndarray.flags       有关阵列的内存布局的信息。
ndarray.shape       数组维度的元组。
ndarray.strides     在遍历数组时在每个维度上步进的字节元组。
ndarray.ndim        数组维数。
ndarray.data        指向数组数据开头的Python缓冲区对象。
ndarray.size        数组中元素的数量。
ndarray.itemsize    一个数组元素的长度（以字节为单位）。
ndarray.nbytes      数组元素消耗的总字节数。
ndarray.base        如果内存来自其他对象，则为基础对象。

In [1]:
import numpy as np

a = np.arange(1,10).reshape((3,3))

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.flags,\
a.shape,\
a.strides,\
a.ndim,\
a.data,\
a.size,\
a.itemsize,\
a.nbytes,\
a.base

(  C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False,
 (3, 3),
 (12, 4),
 2,
 9,
 4,
 36,
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [5]:
"""
real 数组的实部。
imag 数组的虚部。
"""
a.T,\
    a.real,\
    a.imag,\
    a.flat,\
    a.ctypes,\
    a.dtype



(array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 dtype('int32'))

In [6]:
x = np.sqrt([1+0j, 0+1j])
x.imag,x.real


(array([0.        , 0.70710678]), array([1.        , 0.70710678]))

## Array methods
以下方法在numpy中也有相应的函数:
 all, any, argmax, argmin, argpartition, argsort, choose, clip,
 compress, copy, cumprod, cumsum, diagonal, imag, max, mean, min, nonzero,
 partition, prod, ptp, put, ravel, real, repeat, reshape, round,
 searchsorted, sort, squeeze, std, sum, swapaxes, take, trace, transpose, var.

### 转换相关的方法
https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-conversion
ndarray.item（* args）                    将数组的元素复制到标准Python标量并返回。
ndarray.tolist（）                        将数组作为a.ndim-levels深层嵌套的Python标量列表返回。
ndarray.itemset（* args）                 将标量插入数组（如果可能，将标量强制转换为数组的dtype）
ndarray.tostring（[order]）               在数组中构造包含原始数据字节的Python字节。
ndarray.tobytes（[order]）                在数组中构造包含原始数据字节的Python字节。
ndarray.tofile（fid [，sep，format））   将数组以文本或二进制形式写入文件（默认）。
ndarray.dump（file）                  将数组的腌制转储到指定文件中。
ndarray.dumps（）                     以字符串形式返回数组的泡菜。
ndarray.astype（dtype [，order，casting，...]）数组的副本，强制转换为指定的类型。
ndarray.byteswap（[inplace]）         交换数组元素的字节
ndarray.copy（[order]）           返回数组的副本。
ndarray.view（[dtype，type]）      具有相同数据的数组的新视图。
ndarray.getfield（dtype [，Offset]）       以给定类型返回给定数组的字段。
ndarray.setflags（[write, align，uic]）   分别设置数组标志WRITEABLE，ALIGNED（WRITEBACKIFCOPY和UPDATEIFCOPY）。
ndarray.fill（value）             用标量值填充数组。

In [10]:
a.item(3),\
a.tolist(),\
a.itemset((0,1),10),\
a.tolist()



(4,
 [[1, 10, 3], [4, 5, 6], [7, 8, 9]],
 None,
 [[1, 10, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
"""
### 形状操控相关方法
ndarray.reshape（shape [，order]）         返回包含具有新形状的相同数据的数组。
ndarray.resize（new_shape [，refcheck]）   就地更改数组的形状和大小。
ndarray.transpose（* axes）               返回轴已转置的数组视图。
ndarray.swapaxes（axis1，axis2）          返回轴1和轴2互换的数组视图。
ndarray.flatten（[order]）                返回折叠成一维的数组副本。
ndarray.ravel（[order]）                  返回一个展平的数组。
ndarray.squeeze（[axis]）                 从a的形状中删除一维条目。
"""
x = np.arange(0,10).reshape((2,5))
x,x.flatten()


(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [13]:
"""
# item选择和操作相关方法
ndarray.take(index [， axis, out, mode])     返回a中给定下标的元素组成的数组。
ndarray.put(indices, values[, mode])        设置一个。flat[n] =所有n的索引值[n]。
ndarray.repeat(repeats[, axis])             重复数组中的元素。
ndarray.choose(choices[, out, mode])        使用索引数组从一组选项构造一个新数组。
ndarray.sort([axis, kind, order])           就地对数组排序。
ndarray.argsort([axis, kind, order])        返回对数组进行排序的索引。
ndarray.partition(kth[， axis, kind, order])重新排列数组中的元素，使元素在第k个位置的值处于它在排序数组中的位置。
ndarray.argpartition(kth[， axis, kind, order])     返回将对数组进行分区的索引。
ndarray.searchsorted (v[,side, sorter])     找出a中需要插入v元素以维持秩序的下标。
ndarray.nonzero ()                      返回非零元素的索引。
ndarray.compress(condition[, axis, out])  沿着给定的轴返回这个数组的选定的片。
ndarray.diagonal([offset, axis1, axis2])    返回指定的对角线。
"""
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)


array([4, 3, 6])

In [14]:
a = np.array(a)
a[indices]



array([4, 3, 6])

In [15]:
np.take(a, [[0, 1], [2, 3]])

array([[4, 3],
       [5, 7]])

In [16]:
a = np.arange(5)
np.put(a, [0, 2], [-44, -55])
a

array([-44,   1, -55,   3,   4])

In [17]:
a = np.arange(5)
np.put(a, 22, -5, mode='clip')
a
# mode=clip 表示所有太大的索引都被指向该轴上最后一个元素的索引所取代。
# 请注意，这将禁用负数索引。 在“提升”模式下，如果发生异常，则仍可以修改目标数组。


array([ 0,  1,  2,  3, -5])

In [18]:
np.repeat(3, 4)



array([3, 3, 3, 3])

In [20]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2),np.repeat(x, 3, axis=1),np.repeat(x, [1, 2], axis=0)


(array([1, 1, 2, 2, 3, 3, 4, 4]),
 array([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]]),
 array([[1, 2],
        [3, 4],
        [3, 4]]))

In [21]:
choices = [[0, 1, 2, 3], [10, 11, 12, 13],
  [20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 3, 1, 0], choices
# the first element of the result will be the first element of the
# third (2+1) "array" in choices, namely, 20; the second element
# will be the second element of the fourth (3+1) choice array, i.e.,
# 31, etc.
)



array([20, 31, 12,  3])

In [24]:
a = np.array([[1,4], [3,1]])
a.sort(axis=1)
a



array([[1, 4],
       [1, 3]])

In [25]:
a.sort(axis=0)
a



array([[1, 3],
       [1, 4]])

In [26]:
a = np.array([('a', 2), ('c', 1)], dtype=[('x', 'S1'), ('y', int)])
a.sort(order='y')
a



array([(b'c', 1), (b'a', 2)], dtype=[('x', 'S1'), ('y', '<i4')])

In [27]:
x = np.array([3, 1, 2])
np.argsort(x)



array([1, 2, 0], dtype=int64)

In [28]:
"""
ndarray.partition(kth, axis=-1, kind='introselect', order=None)
重新排列数组中的元素，使元素在第k个位置的值处于它在排序数组中的位置。
所有小于第k个元素的元素被移动到这个元素前面，所有大于等于这个元素的元素被移动到它后面。
两个分区中元素的顺序是未定义的。
"""
a = np.array([3, 4, 2, 1])
a.partition(3)
a


array([2, 1, 3, 4])

In [29]:
a.partition((1, 3))
a



array([1, 2, 3, 4])

In [30]:
# 查找应该插入元素以维持顺序的索引。
# 找到排序数组a中的下标，如果v中对应的元素插入到下标之前，a的顺序将保持不变。
# side若为left，则给出找到的第一个合适位置的索引。如果right，返回最后一个这样的索引。如果没有合适的索引，返回0或N(其中N是a的长度)。
np.searchsorted([1,2,3,4,5], 3),\
np.searchsorted([1,2,3,4,5], 3, side='right'),\
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

(2, 3, array([0, 5, 1, 2], dtype=int64))

In [32]:
# 返回非0的x,y 值，比如 1，0 = 4 = true
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a > 3,np.nonzero(a > 3),a[np.nonzero(a > 3)]


(array([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]]),
 (array([1, 1, 1, 2, 2, 2], dtype=int64),
  array([0, 1, 2, 0, 1, 2], dtype=int64)),
 array([4, 5, 6, 7, 8, 9]))

In [33]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
x,np.nonzero(x),x[np.nonzero(x)]



(array([[3, 0, 0],
        [0, 4, 0],
        [5, 6, 0]]),
 (array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64)),
 array([3, 4, 5, 6]))

In [35]:
"""
numpy.compress(condition, a, axis=None, out=None)
沿着给定的轴返回数组中选定的片。当沿着给定的轴工作时，
对于条件为真的每个索引，将在输出中返回沿着该轴的一个切片。当处理一个1-D数组时，压缩相当于提取。
"""
a = np.array([[1, 2], [3, 4], [5, 6]])

a,np.compress([0, 1], a, axis=0),\
np.compress([False, True, True], a, axis=0),\
np.compress([False, True], a, axis=1),\
np.compress([False, True], a)


(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[3, 4]]),
 array([[3, 4],
        [5, 6]]),
 array([[2],
        [4],
        [6]]),
 array([2]))

In [36]:
# 返回满足某些条件的数组元素。这个方法不属于ndarray
# 这相当于np.compress(ravel(condition), ravel(arr)).
arr = np.arange(12).reshape((3, 4))

condition = np.mod(arr, 3)==0
arr,condition,np.extract(condition, arr)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ True, False, False,  True],
        [False, False,  True, False],
        [False,  True, False, False]]),
 array([0, 3, 6, 9]))

In [37]:
# 返回指定的对角线。
a = np.arange(4).reshape(2,2)
a,a.diagonal(),a.diagonal(1)


(array([[0, 1],
        [2, 3]]),
 array([0, 3]),
 array([1]))

In [38]:
a = np.arange(8).reshape(2,2,2)
a,a.diagonal(0,  # Main diagonals of two arrays created by skipping
           0,  # across the outer(left)-most axis last and
           1)  # the "middle" (row) axis first.

(array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[0, 6],
        [1, 7]]))

In [39]:
a[:,:,0]  # main diagonal is [0 6]


array([[0, 2],
       [4, 6]])

In [40]:
a[:,:,1]  # main diagonal is [1 7]



array([[1, 3],
       [5, 7]])

In [41]:
a = np.arange(9).reshape(3, 3)
a,np.fliplr(a).diagonal(),np.flipud(a).diagonal()
# flip 翻转 np.fliplr(a).diagonal()  # Horizontal flip     np.flipud(a).diagonal()  # Vertical flip



(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([2, 4, 6]),
 array([6, 4, 2]))

### Calculation 计算相关方法
https://numpy.org/doc/stable/reference/arrays.ndarray.html#calculation
ndarray.max（[axis, out，keepdims，initial，...]）   沿给定轴返回最大值。
ndarray.argmax（[axis，out]）                      沿给定轴返回最大值的索引。
ndarray.min（[axis, out，keepdims，initial，...]）   沿给定轴返回最小值。
ndarray.argmin（[axis，out]）                      沿a的给定轴返回最小值的索引。
ndarray.ptp（[axis，out，keepdims]）                沿给定轴的峰到峰（最大值-最小值）值。
ndarray.clip（[min，max，out]）                     返回其值限制为[min，max]的数组。
ndarray.conj（）                                  将所有元素复数共轭。
ndarray.round（[decimals，out]）                   返回a，每个元素四舍五入到给定的小数位数。
ndarray.trace（[offset, axis1, axis2, dtype, out]）   返回数组对角线的和。
ndarray.sum（[axis，dtype，out，keepdims，...]）  返回给定轴上数组元素的总和。
ndarray.cumsum（[axis, dtype, out]）              返回沿给定轴的元素的累加和。
ndarray.mean（[axis, dtype, out，keepdims]）       返回沿给定轴的数组元素的平均值。
ndarray.var（[axis，dtype，out，ddof，keepdims]）     返回沿给定轴的数组元素的方差。
ndarray.std（[axis，dtype，out，ddof，keepdims]）     返回沿给定轴的数组元素的标准偏差。
ndarray.prod（[axis，dtype，out，keepdims，...]）     返回给定轴上数组元素的乘积
ndarray.cumprod（[axis，dtype，out]）               返回沿给定轴的元素的累积积。
ndarray.all（[axis，out，keepdims]）            如果所有元素的评估结果为True，则返回True。
ndarray.any（[axis，out，keepdims]）            如果评估的任何元素为True，则返回True。


In [42]:
# decimals 需要四舍五入的小数点位数(默认为0)。如果小数点是负数，则指定小数点左边的位置数。
np.around([0.37, 1.64]),\
np.around([0.37, 1.64], decimals=1),\
np.around([.5, 1.5, 2.5, 3.5, 4.5]),\
np.around([1,2,3,11], decimals=1),\
np.around([1,2,3,11], decimals=-1)


(array([0., 2.]),
 array([0.4, 1.6]),
 array([0., 2., 2., 4., 4.]),
 array([ 1,  2,  3, 11]),
 array([ 0,  0,  0, 10]))