https://numpy.org/doc/stable/reference/arrays.indexing.html


In [4]:
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7],x[1:7:2],x[2:12]



(array([1, 2, 3, 4, 5, 6]), array([1, 3, 5]), array([2, 3, 4, 5, 6, 7, 8, 9]))

In [5]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]]])
x[1:2]



array([[[4],
        [5],
        [6]]])

In [16]:
# Ellipsis 只能出现一个
x = np.array([[[1],[2],[3]], [[4],[5],[6]], [[7],[8],[9]]])
x[...,0],x[...,0][...,2]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([3, 6, 9]))

In [14]:
x = np.random.RandomState(5).randint(200, size=[3, 4, 5])
x[:],x[...],x[:,...]

(array([[[ 99, 189, 118, 144,  73],
         [  8, 190, 155, 112, 158],
         [  7, 143, 113, 181,  80],
         [ 27,  44,  65, 175,  30]],
 
        [[ 86, 125, 146, 121, 137],
         [106,  41, 190, 129, 103],
         [144,   5,  58,   0, 132],
         [110, 164, 105, 179,  27]],
 
        [[ 31,   2,  68,  38, 105],
         [147,  18, 113, 135, 100],
         [108, 109, 158, 190,  11],
         [ 67, 124, 193, 183, 131]]]),
 array([[[ 99, 189, 118, 144,  73],
         [  8, 190, 155, 112, 158],
         [  7, 143, 113, 181,  80],
         [ 27,  44,  65, 175,  30]],
 
        [[ 86, 125, 146, 121, 137],
         [106,  41, 190, 129, 103],
         [144,   5,  58,   0, 132],
         [110, 164, 105, 179,  27]],
 
        [[ 31,   2,  68,  38, 105],
         [147,  18, 113, 135, 100],
         [108, 109, 158, 190,  11],
         [ 67, 124, 193, 183, 131]]]),
 array([[[ 99, 189, 118, 144,  73],
         [  8, 190, 155, 112, 158],
         [  7, 143, 113, 181,  80],
         [

In [18]:
x,x[:,0],x[...,0],x[:,:,0]

(array([[[1],
         [2],
         [3]],
 
        [[4],
         [5],
         [6]],
 
        [[7],
         [8],
         [9]]]),
 array([[1],
        [4],
        [7]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [12]:
x[0,...]
# x[3维][2维][1维]



array([[ 99, 189, 118, 144,  73],
       [  8, 190, 155, 112, 158],
       [  7, 143, 113, 181,  80],
       [ 27,  44,  65, 175,  30]])

In [20]:
x[:,np.newaxis,:,:]
# 选择元组中的每个newaxis对象用于将结果选择的尺寸扩展一个单位长度尺寸。
# 添加的维度是新轴对象在选择元组中的位置。

array([[[[1],
         [2],
         [3]]],


       [[[4],
         [5],
         [6]]],


       [[[7],
         [8],
         [9]]]])

In [23]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x[[0, 1, 2], [0, 1, 0]]


array([1, 4, 5])

In [24]:
x = np.array([[ 0,  1,  2],
           [ 3,  4,  5],
           [ 6,  7,  8],
           [ 9, 10, 11]])
rows = np.array([[0, 0],
                 [3, 3]], dtype=np.intp)
columns = np.array([[0, 2],
                    [0, 2]], dtype=np.intp)
x[rows, columns]



array([[ 0,  2],
       [ 9, 11]])

In [27]:
rows = np.array([0, 3], dtype=np.intp)
columns = np.array([0, 2], dtype=np.intp)

rows[:, np.newaxis],\
x[rows[:, np.newaxis], columns],\
x[np.array([[0], [3]], dtype=np.intp), np.array([0, 2], dtype=np.intp)]


(array([[0],
        [3]], dtype=int64),
 array([[ 0,  2],
        [ 9, 11]]),
 array([[ 0,  2],
        [ 9, 11]]))

In [28]:
x[np.ix_(rows, columns)],\
x[rows, columns]




(array([[ 0,  2],
        [ 9, 11]]),
 array([ 0, 11]))