https://numpy.org/doc/stable/reference/constants.html

常量




In [2]:
import numpy
numpy.Inf,\
numpy.Infinity,\
    numpy.PINF,\
    numpy.infty,\
    numpy.inf
# IEEE 754(正)无穷大的浮点表示。使用inf，因为inf，无穷大，PINF和infty是inf的别名。



(inf, inf, inf, inf, inf)

In [3]:
# IEEE 754非数字的浮点表示(NaN)。NaN和NaN是NaN的等价定义。请用nan代替nan。
numpy.NAN,\
    numpy.nan,\
    numpy.NaN



(nan, nan, nan)

In [4]:
# ieee754 -∞的浮点表示。
numpy.NINF


-inf

In [5]:
numpy.NZERO,numpy.PZERO
# IEEE 754负零的浮点表示。IEEE 754浮点数表示的正零。


(-0.0, 0.0)

In [6]:
numpy.e
# 欧拉常数，自然对数的基础，纳皮尔常数。


2.718281828459045

In [7]:
numpy.euler_gamma
# γ = 0.5772156649015328606065120900824024310421...


0.5772156649015329

In [8]:
numpy.pi

3.141592653589793

In [9]:
#  numpy.newaxis从字面上来理解就是用来创建新轴的，或者说是用来对array进行维度扩展的。
x = numpy.arange(3)
numpy.newaxis,numpy.newaxis is None,\
x,\
x[:, numpy.newaxis],\
x[:, ...],\
x[:, numpy.newaxis, numpy.newaxis],\
x[:, numpy.newaxis] * x

(None,
 True,
 array([0, 1, 2]),
 array([[0],
        [1],
        [2]]),
 array([0, 1, 2]),
 array([[[0]],
 
        [[1]],
 
        [[2]]]),
 array([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]]))

In [10]:
y = numpy.arange(3, 6)
x[:, numpy.newaxis] * y



array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

In [11]:
# x[newaxis, :] is equivalent to x[newaxis] and x[None]:
x[numpy.newaxis, :].shape,\
x[numpy.newaxis].shape,\
x[None].shape,\
x[:, numpy.newaxis].shape



((1, 3), (1, 3), (1, 3), (3, 1))