# Universal functions 通用函数
https://numpy.org/doc/stable/reference/ufuncs.html



In [1]:
import numpy as np

# 打印两种类型之间是否可以转换
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()

print_table(np.typecodes['All'])


X ? b h i l q p B H I L Q P e f d g F D G S U V O M m
? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - - Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y - Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
Q - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - - Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y - -
d - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
g - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
F - - - - - - - - - - - - - 

In [2]:
# 输入参数的数量
np.add.nin,\
np.multiply.nin,\
np.power.nin,\
np.exp.nin




(2, 2, 2, 1)

In [3]:
# 输出数量。

np.add.nout,\
np.multiply.nout,\
np.power.nout,\
np.exp.nout

(1, 1, 1, 1)

In [4]:
# 参数的数量，包括可选参数
np.add.nargs,\
np.multiply.nargs,\
np.power.nargs,\
np.exp.nargs

(3, 3, 3, 2)

In [5]:
# 类型数。ufunc可以在其上进行操作的数字NumPy类型的数量（总共有18种）
np.add.ntypes,\
np.multiply.ntypes,\
np.power.ntypes,\
np.exp.ntypes,\
np.remainder.ntypes


(22, 23, 18, 9, 16)

In [6]:
# 返回一个将输入->输出分组的列表。
np.add.types,\
np.multiply.types,\
np.power.types,\
np.exp.types,\
np.remainder.types


(['??->?',
  'bb->b',
  'BB->B',
  'hh->h',
  'HH->H',
  'ii->i',
  'II->I',
  'll->l',
  'LL->L',
  'qq->q',
  'QQ->Q',
  'ee->e',
  'ff->f',
  'dd->d',
  'gg->g',
  'FF->F',
  'DD->D',
  'GG->G',
  'Mm->M',
  'mm->m',
  'mM->M',
  'OO->O'],
 ['??->?',
  'bb->b',
  'BB->B',
  'hh->h',
  'HH->H',
  'ii->i',
  'II->I',
  'll->l',
  'LL->L',
  'qq->q',
  'QQ->Q',
  'ee->e',
  'ff->f',
  'dd->d',
  'gg->g',
  'FF->F',
  'DD->D',
  'GG->G',
  'mq->m',
  'qm->m',
  'md->m',
  'dm->m',
  'OO->O'],
 ['bb->b',
  'BB->B',
  'hh->h',
  'HH->H',
  'ii->i',
  'II->I',
  'll->l',
  'LL->L',
  'qq->q',
  'QQ->Q',
  'ee->e',
  'ff->f',
  'dd->d',
  'gg->g',
  'FF->F',
  'DD->D',
  'GG->G',
  'OO->O'],
 ['e->e', 'f->f', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O'],
 ['bb->b',
  'BB->B',
  'hh->h',
  'HH->H',
  'ii->i',
  'II->I',
  'll->l',
  'LL->L',
  'qq->q',
  'QQ->Q',
  'ee->e',
  'ff->f',
  'dd->d',
  'gg->g',
  'mm->m',
  'OO->O'])

In [13]:
np.add.identity,\
np.multiply.identity,\
np.power.identity,\
np.exp.identity


(0, 1, None, None)

In [11]:
np.exp.signature,\
np.add.signature



(None, None)

In [ ]:
# reduce 通过沿一个轴应用ufunc，将s维减少1。
np.multiply.reduce([2,3,5])



In [14]:
X = np.arange(8).reshape((2,2,2))
X,\
np.add.reduce(X, 0),\
np.add.reduce(X),\
np.add.reduce(X, 1),\
np.add.reduce(X, 2)



(array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[ 4,  6],
        [ 8, 10]]),
 array([[ 4,  6],
        [ 8, 10]]),
 array([[ 2,  4],
        [10, 12]]),
 array([[ 1,  5],
        [ 9, 13]]))

In [15]:
a = np.array([10., np.nan, 10])
np.add.reduce([10], initial=5),\
np.add.reduce(np.ones((2, 2, 2)), axis=(0, 2), initial=10),\
np.add.reduce(a, where=~np.isnan(a))



(15, array([14., 14.]), 20.0)

In [16]:
# 累积将运算符应用于所有元素的结果。
np.add.accumulate([2, 3, 5]),\
np.multiply.accumulate([2, 3, 5])


(array([ 2,  5, 10], dtype=int32), array([ 2,  6, 30], dtype=int32))

In [17]:
I = np.eye(2)
I,np.add.accumulate(I, 0),np.add.accumulate(I),np.add.accumulate(I, 1)



(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [1., 1.]]),
 array([[1., 0.],
        [1., 1.]]),
 array([[1., 1.],
        [0., 1.]]))

In [19]:
# 在单个轴上使用指定的片执行(本地)reduce。
# If a is 1-D, the function ufunc.accumulate(a) is the same as ufunc.reduceat(a, indices)[::2] where indices is range(len(array) - 1)
# with a zero placed in every other element:
# indices = zeros(2 * len(a) - 1), indices[1::2] = range(1, len(a)).
# https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html#numpy.ufunc.reduceat
np.arange(8),\
np.add.reduceat(np.arange(8),[0,4, 1,5, 2,6, 3,7]),\
np.add.reduceat(np.arange(8),[0,4, 1,5, 2,6, 3,7])[::2]

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 6,  4, 10,  5, 14,  6, 18,  7], dtype=int32),
 array([ 6, 10, 14, 18], dtype=int32))

In [20]:
# reduceat方法需要输入一个数组以及一个索引值列表作为参数
B = np.arange(9)
B3 = np.add.reduceat(B,[0,5,2,7])
print (B3)
# [10 5 20 15]
# 解析：第一步用到索引值列表中的0和5，实际上就是对数组中索引值在0到5之间的元素进行reduce操作。
print (np.add.reduce(B[0:5]))
# 第二步用到索引值5和2。由于2比5小，所以直接返回索引值为5的元素
print (np.add.reduce(B[5]))
# 第三步用到索引值2和7。这一步是对索引值在2到7之间的数组元素进行reduce操作
print (np.add.reduce(B[2:7]))
# 第四步用到索引值7。这一步是对索引值从7开始直到数组末端的元素进行reduce操作
print (np.add.reduce(B[7:]))



[10  5 20 15]
10
5
20
15


In [22]:
# 将ufunc op应用于A中的a和b中的b的所有对（a，b）。
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3, 4]])
C = np.multiply.outer(A, B)

np.multiply.outer([1, 2, 3], [4, 5, 6]),C.shape, C


(array([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]]),
 (2, 3, 1, 4),
 array([[[[ 1,  2,  3,  4]],
 
         [[ 2,  4,  6,  8]],
 
         [[ 3,  6,  9, 12]]],
 
 
        [[[ 4,  8, 12, 16]],
 
         [[ 5, 10, 15, 20]],
 
         [[ 6, 12, 18, 24]]]]))

In [25]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([1, 2, 3, 4])

np.negative.at(a1, [0, 1])
np.add.at(a2, [0, 1, 2, 2], 1)

a = np.array([1, 2, 3, 4])
b = np.array([1, 2])
np.add.at(a, [0, 1], b)


a1,a2,a



(array([-1, -2,  3,  4]), array([2, 3, 5, 4]), array([2, 4, 3, 4]))

# Available ufuncs
https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs

In [ ]:
# 数学运算   三角函数


