In [1]:
# https://numpy.org/doc/stable/reference/routines.array-manipulation.html#changing-kind-of-array
import numpy as np
a = [1, 2]
np.asarray(a)

array([1, 2])

In [2]:
a = np.array([1, 2])
np.asarray(a) is a

True

In [3]:
a = np.array([1, 2], dtype=np.float32)
np.asarray(a, dtype=np.float32) is a,\
np.asarray(a, dtype=np.float64) is a



(True, False)

In [4]:

a = np.array([(1.0, 2), (3.0, 4)], dtype='f4,i4').view(np.recarray)
issubclass(np.recarray, np.ndarray),\
np.asarray(a) is a,\
np.asanyarray(a) is a


(True, False, True)

In [5]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
x[0,0] = 5
m

matrix([[5, 2],
        [3, 4]])

In [6]:
# 返回转换为浮点类型的数组。
np.asfarray([2, 3]),\
np.asfarray([2, 3], dtype='float'),\
np.asfarray([2, 3], dtype='int8')


(array([2., 3.]), array([2., 3.]), array([2., 3.]))

In [7]:
# 返回一个数组(ndim >= 1)在内存中以Fortran格式排列。
x = np.arange(6).reshape(2,3)
y = np.asfortranarray(x)
x.flags['F_CONTIGUOUS'],\
y.flags['F_CONTIGUOUS']


(False, True)

In [8]:
# 返回内存中的连续数组(ndim >= 1) (C顺序)。
x = np.arange(6).reshape(2,3)
np.ascontiguousarray(x, dtype=np.float32),\
x.flags['C_CONTIGUOUS']


(array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32),
 True)

In [9]:
# 将输入转换为数组，检查nan或Infs。
a1 = [1, 2]
a2 = [1, 2, np.inf]
try:
    np.asarray_chkfinite(a2)
except ValueError:
    print('ValueError')

np.asarray_chkfinite(a1, dtype=float)

ValueError


array([1., 2.])

In [10]:
# 将大小为1的数组转换为其等效标量。
np.asscalar(np.array([24]))

d:\programdata\miniconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  


24

In [11]:
"""
numpy.require(a, dtype=None, requirements=None)
返回提供的类型满足要求的ndarray。
确保返回具有正确标志的数组以传递给编译后的代码（也许通过ctypes）时，此函数很有用。
"""
x = np.arange(6).reshape(2,3)
y = np.require(x, dtype=np.float32, requirements=['A', 'O', 'W', 'F'])

x.flags,y.flags


(  C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False,
   C_CONTIGUOUS : False
   F_CONTIGUOUS : True
   OWNDATA : True
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False
   UPDATEIFCOPY : False)

In [12]:
# 沿着现有的轴连接数组序列。
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0),\
np.concatenate((a, b.T), axis=1),\
np.concatenate((a, b), axis=None)


(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2, 5],
        [3, 4, 6]]),
 array([1, 2, 3, 4, 5, 6]))

In [13]:
# 沿新轴连接一系列数组。
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b)),np.stack((a, b), axis=-1)


(array([[1, 2, 3],
        [2, 3, 4]]),
 array([[1, 2],
        [2, 3],
        [3, 4]]))

In [14]:
"""
堆栈1-D数组作为列到2-D数组。

取一个1-D数组序列，并将它们作为列堆叠成一个2-D数组。
二维数组按原样堆叠，就像hstack一样。首先将一维数组转换为二维列。
"""
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

# https://numpy.org/doc/stable/reference/routines.array-manipulation.html#joining-arrays

array([[1, 2],
       [2, 3],
       [3, 4]])

In [16]:
x1 = np.arange(9.0)
x2 = np.arange(8.0)
np.split(x2, [3, 5, 6, 10]),\
np.split(x1, 3)



([array([0., 1., 2.]),
  array([3., 4.]),
  array([5.]),
  array([6., 7.]),
  array([], dtype=float64)],
 [array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])])

In [17]:
# numpy.tile(A, reps)通过重复A代表次数来构造一个数组。
a = np.array([0, 1, 2])
np.tile(a, 2),\
np.tile(a, (2, 2)),\
np.tile(a, (2, 1, 2))

(array([0, 1, 2, 0, 1, 2]),
 array([[0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2]]),
 array([[[0, 1, 2, 0, 1, 2]],
 
        [[0, 1, 2, 0, 1, 2]]]))

In [18]:
x = np.array([[1,2],[3,4]])
np.repeat(3, 4),\
np.repeat(x, 2),\
np.repeat(x, 3, axis=1),\
np.repeat(x, [1, 2], axis=0)


(array([3, 3, 3, 3]),
 array([1, 1, 2, 2, 3, 3, 4, 4]),
 array([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]]),
 array([[1, 2],
        [3, 4],
        [3, 4]]))

In [19]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr,np.delete(arr, 1, 0)


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]]))

In [20]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)



array([1, 2, 3, 0, 2, 1])

In [21]:
a = np.array([[1, 1], [2, 3]])
np.unique([1, 1, 2, 2, 3, 3]),np.unique(a)


(array([1, 2, 3]), array([1, 2, 3]))

In [22]:
# 沿着给定的轴颠倒数组中元素的顺序。数组的形状被保留，但是元素被重新排序。
A = np.arange(8).reshape((2,2,2))
A,\
np.flip(A, 0),\
np.flip(A, 1),\
np.flip(A),\
np.flip(A, (0, 2))


(array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[4, 5],
         [6, 7]],
 
        [[0, 1],
         [2, 3]]]),
 array([[[2, 3],
         [0, 1]],
 
        [[6, 7],
         [4, 5]]]),
 array([[[7, 6],
         [5, 4]],
 
        [[3, 2],
         [1, 0]]]),
 array([[[5, 4],
         [7, 6]],
 
        [[1, 0],
         [3, 2]]]))