# 数组常规操作
https://numpy.org/doc/stable/reference/routines.html
https://numpy.org/doc/stable/reference/routines.array-manipulation.html




In [2]:
import numpy as np
# numpy.copyto(dst, src, casting='same_kind', where=True)

src = np.array([1,2,2])
dst = np.empty_like([1,2,3])
np.copyto(dst,src)
dst

array([1, 2, 2])

In [3]:
np.shape(np.eye(3)),\
np.shape([[1, 2]]),\
np.shape([0]),\
np.shape(0)



((3, 3), (1, 2), (1,), ())

In [ ]:
a = np.arange(6).reshape((3, 2))



In [4]:
"""
numpy.ravel(a, order='C')
返回一个连续的扁平数组。
返回包含输入元素的一维数组。 仅在需要时才进行复制。
从NumPy 1.10开始，返回的数组将具有与输入数组相同的类型。 （例如，将为掩码数组输入返回一个掩码数组）

numpy.flatten()返回一份拷贝，对拷贝所做的修改不会影响（reflects）原始矩阵，
而numpy.ravel()返回的是视图（view，也颇有几分C/C++引用reference的意味），会影响（reflects）原始矩阵。
See also
ndarray.flat
1-D iterator over an array.

ndarray.flatten
1-D array copy of the elements of an array in row-major order.

ndarray.reshape
Change the shape of an array without changing its data.
"""

x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x),\
x.reshape(-1),\
np.ravel(x, order='F'),\
np.ravel(x.T),\
np.ravel(x.T, order='A')



(array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4, 5, 6]),
 array([1, 4, 2, 5, 3, 6]),
 array([1, 4, 2, 5, 3, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [8]:
"""
numpy.moveaxis(a, source, destination)

See also
transpose
Permute the dimensions of an array.
swapaxes 交换维度
Interchange two axes of an array.
"""
x = np.zeros((3, 4, 5))
np.moveaxis(x, 0, -1).shape,\
np.moveaxis(x, -1, 0).shape,\
np.transpose(x).shape,\
np.swapaxes(x, 0, -1).shape,\
np.moveaxis(x, [0, 1], [-1, -2]).shape,\
np.moveaxis(x, [0, 1, 2], [-1, -2, -3]).shape

# np.moveaxis(x, 0, -1)   将第一个轴移动到最后一个位置。
# np.rollaxis(first_stacked, 0, first_stacked.ndim) 你可以把轴滚到想要的位置。

((4, 5, 3), (5, 3, 4), (5, 4, 3), (5, 4, 3), (5, 4, 3), (5, 4, 3))

In [9]:
"""
numpy.rollaxis(a, axis, start=0)
向后滚动指定的轴，直到其位于给定的位置。

See also
moveaxis
Move array axes to new positions.
roll
Roll the elements of an array by a number of positions along a given axis.
"""
a = np.ones((3,4,5,6))
np.rollaxis(a, 3, 1).shape,\
np.rollaxis(a, 2).shape,\
np.rollaxis(a, 1, 4).shape

((3, 6, 4, 5), (5, 3, 4, 6), (3, 5, 6, 4))

In [10]:
"""
numpy.roll(a, shift, axis=None)
沿给定轴的滚动阵列单元。超过最后一个位置的元素将在第一个位置重新引入。
"""
x = np.arange(10)
x,np.roll(x, 2),np.roll(x, -2)


(array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7]), array([2, 3, 4, 5, 6, 7, 8, 9, 0, 1]))

In [11]:
x2 = np.reshape(x, (2,5))
x2,\
np.roll(x2, 1),\
np.roll(x2, -1),\
np.roll(x2, 1, axis=0),\
np.roll(x2, -1, axis=0),\
np.roll(x2, 1, axis=1),\
np.roll(x2, -1, axis=1)



(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[9, 0, 1, 2, 3],
        [4, 5, 6, 7, 8]]),
 array([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]]),
 array([[5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]]),
 array([[4, 0, 1, 2, 3],
        [9, 5, 6, 7, 8]]),
 array([[1, 2, 3, 4, 0],
        [6, 7, 8, 9, 5]]))

In [12]:
"""
numpy.swapaxes(a, axis1, axis2)
"""
x = np.array([[1,2,3]])
x2 = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

np.swapaxes(x,0,1),x2,np.swapaxes(x2,0,2)


(array([[1],
        [2],
        [3]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]),
 array([[[0, 4],
         [2, 6]],
 
        [[1, 5],
         [3, 7]]]))

In [13]:
"""
numpy.transpose(a, axes=None)
"""
x = np.array([[1.,2.],[3.,4.]])
x,x.T

(array([[1., 2.],
        [3., 4.]]),
 array([[1., 3.],
        [2., 4.]]))

In [14]:
x = np.arange(4).reshape((2,2))
x,np.transpose(x)


(array([[0, 1],
        [2, 3]]),
 array([[0, 2],
        [1, 3]]))

In [16]:
x = np.ones((1, 2, 3))
x,x.shape,np.transpose(x, (1, 0, 2)).shape


(array([[[1., 1., 1.],
         [1., 1., 1.]]]),
 (1, 2, 3),
 (2, 1, 3))

In [17]:
"""
numpy.atleast_1d(*arys)
将输入转换为至少一维的数组。标量输入被转换为一维数组，而高维输入被保留。
"""

x = np.arange(9.0).reshape(3,3)

np.atleast_1d(1.0),\
np.atleast_1d(x),\
np.atleast_1d(x) is x,\
np.atleast_1d(1, [3, 4])


(array([1.]),
 array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 True,
 [array([1]), array([3, 4])])

In [18]:
"""
numpy.atleast_2d(*arys)
将输入视为至少具有两个维度的数组。

numpy.atleast_3d(*arys)
将输入视为至少具有三个维度的数组。
"""
x = np.arange(3.0)

np.atleast_2d(3.0),\
np.atleast_2d(x),\
np.atleast_2d(x).base is x,\
np.atleast_2d(1, [1, 2], [[1, 2]])

(array([[3.]]),
 array([[0., 1., 2.]]),
 True,
 [array([[1]]), array([[1, 2]]), array([[1, 2]])])

In [20]:
"""
class numpy.broadcast
制作一个模拟广播的物体。
"""
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
b,b.index,b.shape,b.size,b.nd,b.ndim,b.numiter,b.iters

(<numpy.broadcast at 0x25b28d87070>,
 0,
 (3, 3),
 9,
 2,
 2,
 2,
 (<numpy.flatiter at 0x25b29049a00>, <numpy.flatiter at 0x25b291112c0>))

In [21]:
out = np.empty(b.shape)
out.flat = [u+v for (u,v) in b]
out,x + y

(array([[5., 6., 7.],
        [6., 7., 8.],
        [7., 8., 9.]]),
 array([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]]))

In [22]:
"""
numpy.broadcast_to(array, shape, subok=False)
"""
x = np.array([1, 2, 3])
np.broadcast_to(x, (3, 3))


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [23]:
"""
numpy.broadcast_arrays(*args, **kwargs)
互相广播任意数量的数组。
"""
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)


[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]])]

In [27]:
a = np.array([1, 2, 3])
print(a.shape)
"""
（1）当axis = 0 时，我们从最高维扩展数组（增加它的维度），就给它在最外面再添个括号就可以啦。所以，
b = np.expand_dims(a, axis=0)
b = [[1, 2, 3]]
b.shape = (1, 3)
shape（1，3）表示从左至右（从高维到低维：axis = 0 , 1）所包含内容的情况，axis = 0（最外面的括号）只包含一个内容：[1, 2, 3]; axis = 1（第二个括号）里包含三个内容：1,  2，3。

（2）当axis = 1 时， 只有第0维有括号，所以当axis = 1就是给里面的数加括号啦

c = np.expand_dims(a, axis=1)
c = [[1], [2], [3]]
c.shape = (3, 1)

（3）当axis = 2时，我们可以发现，我们没有地方加括号，所以它还是和axis=1的情况一样。并且程序会提示：（以后会报错）


2.我们再来看二维数组, axis = 0, 1, 2的情况

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
# a.shape(2, 3)

那么，
（1）当axis = 0 时，我们从最高维扩展数组（增加它的维度），就给它在最外面再添个括号就可以啦。
所以，
b = np.expand_dims(a, axis=0)
b = [[[1, 2, 3], [4, 5, 6]]]
b.shape = (1, 2, 3)

shape（1, 2, 3）表示从左至右（从高维到低维：axis = 0 , 1,  2）所包含内容的情况，axis = 0（最外面的括号）只包含1个内容：[[1, 2, 3], [4, 5, 6]];
axis = 1（第二个括号）里包含2个内容：[1, 2, 3], [4, 5, 6]。axis = 3（第三个括号）里包含3个内容：1， 2， 3；或4，5， 6
（2）当axis = 1 时，就是给第二个括号再加一个括号啦
c = np.expand_dims(a, axis=1)
c = [[[1, 2, 3]], [[4, 5, 6]]]
c.shape = (2, 1, 3)

（3）当axis = 2 时，就是给最里面的数加一个括号。
d = np.expand_dims(a, axis=2)
d = [[[1], [2], [3]], [[4], [5], [6]]]
d.shape = (2, 3, 1)
"""


x = np.array([1, 2])
y = np.expand_dims(x, axis=0)
x,y,\
np.expand_dims(x, axis=1),\
np.expand_dims(x, axis=(0, 1)),\
np.expand_dims(x, axis=(2, 0)),\
    x.shape,y.shape,\
np.expand_dims(x, axis=1).shape,\
np.expand_dims(x, axis=(0, 1)).shape,\
np.expand_dims(x, axis=(2, 0)).shape

(array([1, 2]),
 array([[1, 2]]),
 array([[1],
        [2]]),
 array([[[1, 2]]]),
 array([[[1],
         [2]]]),
 (2,),
 (1, 2),
 (2, 1),
 (1, 1, 2),
 (1, 2, 1))

In [29]:
# squeeze挤压 从数组的形状中删除一维项。
# np.expand_dims  np.squeeze, 这两个函数互为逆操作
y.squeeze(axis=0),\
np.expand_dims(x, axis=1).squeeze(axis=1)



(array([1, 2]), array([1, 2]))

In [31]:
x = np.array([[[0], [1], [2]]])

np.squeeze(x),np.squeeze(x, axis=0),np.squeeze(x, axis=2)

(array([0, 1, 2]),
 array([[0],
        [1],
        [2]]),
 array([[0, 1, 2]]))