https://numpy.org/doc/stable/reference/routines.bitwise.html
# 二进制操作

In [2]:
import numpy as np

np.bitwise_and(13, 17),np.bitwise_and(14, 13),\
np.binary_repr(12),\
np.bitwise_and([14,3], 13),\
    np.bitwise_and([True, True], [False, True])

"""
The number 13 is represented by 00001101. Likewise, 17 is represented by 00010001.
The bit-wise AND of 13 and 17 is therefore 000000001, or 1:
"""

(1, 12, '1100', array([12,  1], dtype=int32), array([False,  True]))

In [ ]:
"""
The number 13 has the binaray representation 00001101. Likewise, 16 is represented by 00010000.
The bit-wise OR of 13 and 16 is then 000111011, or 29:
"""
np.bitwise_or(13, 16),\
np.binary_repr(29)

In [3]:
"""
^ 按位异或
The number 13 is represented by 00001101. Likewise, 17 is represented by 00010001.
The bit-wise XOR of 13 and 17 is therefore 00011100, or 28:
"""
np.bitwise_xor(13, 17),\
np.binary_repr(28)

'\nThe number 13 is represented by 00001101. Likewise, 17 is represented by 00010001. \nThe bit-wise XOR of 13 and 17 is therefore 00011100, or 28:\n'

In [4]:
"""
~ 按位取反
We’ve seen that 13 is represented by 00001101
"""
x = np.invert(np.array(13, dtype=np.uint8))
x,\
np.binary_repr(x, width=8)


(242, '11110010')

In [ ]:
# 左移
np.binary_repr(5),\
np.left_shift(5, 2),\
np.binary_repr(20)


In [ ]:
# 右移
np.binary_repr(10),\
np.right_shift(10, 1),\
np.binary_repr(5)



In [5]:
# 将二进制值数组的元素打包为uint8数组中的位。
a = np.array([[[1,0,1],
               [0,1,0]],
              [[1,1,0],
               [0,0,1]]])
b = np.packbits(a, axis=-1)
b
# Note that in binary 160 = 1010 0000, 64 = 0100 0000, 192 = 1100 0000, and 32 = 0010 0000.

array([[[160],
        [ 64]],

       [[192],
        [ 32]]], dtype=uint8)

In [6]:
a = np.array([[2], [7], [23]], dtype=np.uint8)

b = np.unpackbits(a, axis=1)

c = np.unpackbits(a, axis=1, count=-3)

a,b,c

(array([[ 2],
        [ 7],
        [23]], dtype=uint8),
 array([[0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 1, 1],
        [0, 0, 0, 1, 0, 1, 1, 1]], dtype=uint8),
 array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0]], dtype=uint8))