# 浮点错误处理
https://numpy.org/doc/stable/reference/routines.err.html


In [1]:
# 设置浮点错误的处理方式。
import numpy as np
old_settings = np.seterr(all='ignore')  #seterr to known value
np.seterr(over='raise'),\
np.seterr(**old_settings)  # reset to default

({'divide': 'ignore',
  'over': 'ignore',
  'under': 'ignore',
  'invalid': 'ignore'},
 {'divide': 'ignore', 'over': 'raise', 'under': 'ignore', 'invalid': 'ignore'})

In [2]:
print(np.int16(32000) * np.int16(3))

old_settings = np.seterr(all='warn', over='raise')
np.int16(32000) * np.int16(3)



30464


d:\programdata\miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in short_scalars
  """Entry point for launching an IPython kernel.


FloatingPointError: overflow encountered in short_scalars

In [3]:
from collections import OrderedDict
sorted(np.geterr().items()),\
np.arange(3.) / np.arange(3.)

d:\programdata\miniconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


([('divide', 'warn'),
  ('invalid', 'warn'),
  ('over', 'raise'),
  ('under', 'warn')],
 array([nan,  1.,  1.]))

In [4]:
oldsettings = np.seterr(all='warn', over='raise')
OrderedDict(sorted(np.geterr().items())),\
np.arange(3.) / np.arange(3.)



d:\programdata\miniconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


(OrderedDict([('divide', 'warn'),
              ('invalid', 'warn'),
              ('over', 'raise'),
              ('under', 'warn')]),
 array([nan,  1.,  1.]))

In [5]:
def err_handler(type, flag):
    print("Floating point error (%s), with flag %s" % (type, flag))

saved_handler = np.seterrcall(err_handler)
save_err = np.seterr(all='call')
from collections import OrderedDict
np.array([1, 2, 3]) / 0.0


Floating point error (divide by zero), with flag 1


array([inf, inf, inf])

In [7]:
from collections import OrderedDict
olderr = np.seterr(all='ignore')  # Set error handling to known state.

print(np.arange(3) / 0.)

with np.errstate(divide='warn'):
    print(np.arange(3) / 0.)

[nan inf inf]
[nan inf inf]


d:\programdata\miniconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in true_divide
  import sys


In [8]:
old_errobj = np.geterrobj()  # first get the defaults
old_errobj



[8192, 0, <function __main__.err_handler(type, flag)>]

In [9]:
def err_handler(type, flag):
    print("Floating point error (%s), with flag %s" % (type, flag))

new_errobj = [20000, 12, err_handler]
np.seterrobj(new_errobj)
np.base_repr(12, 8),\
np.geterr(),\
np.geterrcall() is err_handler



('14',
 {'divide': 'print', 'over': 'warn', 'under': 'ignore', 'invalid': 'ignore'},
 True)